import java.util.*;
public class Main {
	public static void main(String[] args) {
		Scanner sc=new Scanner(System.in);
		final int n=8;
		String[] ary=new String[n];
		for (int i=0; i<n; i++) {
			ary[i]=sc.next();
		}
		for (int y=0; y<n; y++) {
			for (int x=0; x<n; x++) {
				String s=ary[y];
				int idx=s.indexOf("*");
				if (idx>=0) {
					String ans="abcdefgh".substring(idx, idx+1);
					ans+=n-y;
					System.out.println(ans);
					System.exit(0);
				}
			}
		}
	}
}
/*
........
........
........
........
........
........
........
*.......

........
........
........
........
........
.*......
........
........
*/
